CREATE DATABASE IF NOT EXISTS asset_management;
USE asset_management;

CREATE TABLE roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);
CREATE TABLE bases (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  location VARCHAR(150) NOT NULL
);
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(120) NOT NULL,
  role_id INT NOT NULL,
  base_id INT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  FOREIGN KEY(role_id) REFERENCES roles(id),
  FOREIGN KEY(base_id) REFERENCES bases(id)
);
CREATE TABLE equipment_types (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  category VARCHAR(80) NOT NULL
);
CREATE TABLE assets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  asset_code VARCHAR(80) NOT NULL UNIQUE,
  equipment_type_id INT NOT NULL,
  base_id INT NOT NULL,
  status VARCHAR(40) DEFAULT 'AVAILABLE',
  quantity INT DEFAULT 1,
  purchase_cost DECIMAL(14,2) NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(equipment_type_id) REFERENCES equipment_types(id),
  FOREIGN KEY(base_id) REFERENCES bases(id)
);
CREATE TABLE purchases (
  id INT AUTO_INCREMENT PRIMARY KEY,
  base_id INT NOT NULL,
  equipment_type_id INT NOT NULL,
  quantity INT NOT NULL,
  unit_cost DECIMAL(14,2) NULL,
  purchase_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  reference VARCHAR(120) NULL,
  FOREIGN KEY(base_id) REFERENCES bases(id),
  FOREIGN KEY(equipment_type_id) REFERENCES equipment_types(id)
);
CREATE TABLE transfers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  asset_id INT NOT NULL,
  from_base_id INT NOT NULL,
  to_base_id INT NOT NULL,
  quantity INT NOT NULL,
  transferred_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  notes TEXT NULL,
  FOREIGN KEY(asset_id) REFERENCES assets(id),
  FOREIGN KEY(from_base_id) REFERENCES bases(id),
  FOREIGN KEY(to_base_id) REFERENCES bases(id)
);
CREATE TABLE assignments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  asset_id INT NOT NULL,
  personnel_name VARCHAR(120) NOT NULL,
  quantity INT NOT NULL,
  assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  returned_at DATETIME NULL,
  FOREIGN KEY(asset_id) REFERENCES assets(id)
);
CREATE TABLE expenditures (
  id INT AUTO_INCREMENT PRIMARY KEY,
  asset_id INT NOT NULL,
  quantity INT NOT NULL,
  reason VARCHAR(255) NOT NULL,
  expended_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(asset_id) REFERENCES assets(id)
);
CREATE TABLE audit_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  action VARCHAR(80) NOT NULL,
  entity VARCHAR(80) NOT NULL,
  entity_id INT NULL,
  details TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id)
);

INSERT INTO roles(name) VALUES ('ADMIN'),('BASE_COMMANDER'),('LOGISTICS_OFFICER');
INSERT INTO bases(name,location) VALUES ('Alpha Base','North Sector'),('Bravo Base','Central Sector'),('Charlie Base','South Sector');
INSERT INTO equipment_types(name,category) VALUES ('Utility Vehicle','Vehicle'),('Communication Equipment','Equipment'),('Protective Equipment','Equipment'),('General Stores','Supply');

-- Demo passwords are PBKDF2 hashes generated by backend/seed.py.
-- Run `python seed.py` to create demo users safely.
