import React, {useEffect, useState} from 'react';
import {api, login} from './services/api';

const nav = [
  ['Dashboard','dashboard'],['Purchases','purchases'],['Transfers','transfers'],['Assignments','assignments'],['Expenditures','expenditures'],['Assets','assets']
];

function Login({onLogin}){
  const [username,setUsername]=useState('admin'); const [password,setPassword]=useState('Admin@123'); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{const d=await login(username,password);localStorage.setItem('token',d.access_token);localStorage.setItem('user',JSON.stringify(d.user));onLogin(d.user)}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <div className="login-page"><div className="login-card"><div className="brand-mark">AM</div><h1>Asset Management</h1><p className="muted">Secure inventory and logistics dashboard</p><form onSubmit={submit}><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} /></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label>{error&&<div className="error">{error}</div>}<button className="primary full" disabled={busy}>{busy?'Signing in...':'Sign in'}</button></form><div className="demo">Demo: admin / Admin@123</div></div></div>
}

function App(){
  const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('user')||'null'));
  const [page,setPage]=useState('dashboard');
  if(!user) return <Login onLogin={setUser}/>;
  function logout(){localStorage.clear();setUser(null)}
  return <div className="app"><aside><div className="side-brand"><span>AM</span><div><strong>Asset</strong><small>Management</small></div></div><div className="nav">{nav.map(([label,key])=><button key={key} className={page===key?'active':''} onClick={()=>setPage(key)}>{label}</button>)}{user.role==='ADMIN'&&<button className={page==='audit'?'active':''} onClick={()=>setPage('audit')}>Audit Logs</button>}</div><div className="side-bottom"><div className="user-mini"><div className="avatar">{user.full_name?.[0]}</div><div><strong>{user.full_name}</strong><small>{user.role.replace('_',' ')}</small></div></div><button className="logout" onClick={logout}>Log out</button></div></aside><main><header><div><h2>{page==='dashboard'?'Dashboard':page[0].toUpperCase()+page.slice(1)}</h2><span className="muted">{user.role.replace('_',' ')}{user.base_id?` • Base ${user.base_id}`:''}</span></div><div className="status-dot">System online</div></header><section className="content"><Page page={page} user={user}/></section></main></div>
}

function Page({page,user}){if(page==='dashboard')return <Dashboard/>; if(page==='purchases')return <Purchases/>; if(page==='transfers')return <Transfers/>; if(page==='assignments')return <Assignments/>; if(page==='expenditures')return <Expenditures/>; if(page==='assets')return <Assets/>; return <Audit/>}

function Dashboard(){
 const [data,setData]=useState(null); const [detail,setDetail]=useState(null); const [filters,setFilters]=useState({});
 useEffect(()=>{load()},[filters]); async function load(){try{const q=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));setData(await api('/dashboard?'+q))}catch(e){}};
 if(!data)return <Loader/>; const cards=[['Opening Balance',data.opening_balance],['Closing Balance',data.closing_balance],['Purchases',data.purchases],['Transfer In',data.transfer_in],['Transfer Out',data.transfer_out],['Assigned',data.assigned_assets],['Expended',data.expended_assets]];
 return <><div className="toolbar"><select onChange={e=>setFilters({...filters,base_id:e.target.value})}><option value="">All bases</option><option value="1">Alpha Base</option><option value="2">Bravo Base</option><option value="3">Charlie Base</option></select><input type="date" onChange={e=>setFilters({...filters,date_from:e.target.value})}/><input type="date" onChange={e=>setFilters({...filters,date_to:e.target.value})}/></div><div className="cards">{cards.map(([k,v])=><div className="card" key={k}><span>{k}</span><strong>{v}</strong></div>)}<button className="card net" onClick={async()=>setDetail(await api('/dashboard/net-movement'))}><span>Net Movement</span><strong>{data.net_movement}</strong><small>Click for details</small></button></div>{detail&&<Modal title="Net Movement Details" onClose={()=>setDetail(null)}><h4>Recent purchases</h4><Table rows={detail.purchases} columns={['date','base','equipment_type','quantity']}/><h4>Recent transfers</h4><Table rows={detail.transfers} columns={['date','from','to','quantity']}/></Modal>}</>
}

function Purchases(){const [rows,setRows]=useState([]);const [bases,setBases]=useState([]);const [types,setTypes]=useState([]);const [form,setForm]=useState({quantity:1});const [msg,setMsg]=useState('');useEffect(()=>{Promise.all([api('/purchases'),api('/bases'),api('/equipment-types')]).then(([r,b,t])=>{setRows(r);setBases(b);setTypes(t)})},[]);async function submit(e){e.preventDefault();try{await api('/purchases',{method:'POST',body:JSON.stringify({...form,base_id:+form.base_id,equipment_type_id:+form.equipment_type_id,quantity:+form.quantity,unit_cost:form.unit_cost?+form.unit_cost:null})});setMsg('Purchase recorded');setRows(await api('/purchases'))}catch(e){setMsg(e.message)}}return <Module title="Record purchase" msg={msg}><Form onSubmit={submit}><Select label="Base" options={bases} value={form.base_id} onChange={v=>setForm({...form,base_id:v})}/><Select label="Equipment type" options={types} value={form.equipment_type_id} onChange={v=>setForm({...form,equipment_type_id:v})}/><Input label="Quantity" type="number" value={form.quantity} onChange={v=>setForm({...form,quantity:v})}/><Input label="Unit cost" type="number" value={form.unit_cost||''} onChange={v=>setForm({...form,unit_cost:v})}/><Input label="Reference" value={form.reference||''} onChange={v=>setForm({...form,reference:v})}/><button className="primary">Save purchase</button></Form><Table title="Purchase history" rows={rows} columns={['id','base','equipment_type','quantity','unit_cost','purchase_date','reference']}/></Module>}

function Transfers(){const [rows,setRows]=useState([]);const [assets,setAssets]=useState([]);const [bases,setBases]=useState([]);const [form,setForm]=useState({quantity:1});const [msg,setMsg]=useState('');useEffect(()=>{Promise.all([api('/transfers'),api('/assets'),api('/bases')]).then(([r,a,b])=>{setRows(r);setAssets(a);setBases(b)})},[]);async function submit(e){e.preventDefault();try{await api('/transfers',{method:'POST',body:JSON.stringify({...form,asset_id:+form.asset_id,to_base_id:+form.to_base_id,quantity:+form.quantity})});setMsg('Transfer completed');setRows(await api('/transfers'));setAssets(await api('/assets'))}catch(e){setMsg(e.message)}}return <Module title="Transfer asset" msg={msg}><Form onSubmit={submit}><Select label="Asset" options={assets.map(a=>({...a,id:a.id,name:`${a.asset_code} — ${a.equipment_type} (${a.quantity})`}))} value={form.asset_id} onChange={v=>setForm({...form,asset_id:v})}/><Select label="Destination base" options={bases} value={form.to_base_id} onChange={v=>setForm({...form,to_base_id:v})}/><Input label="Quantity" type="number" value={form.quantity} onChange={v=>setForm({...form,quantity:v})}/><Input label="Notes" value={form.notes||''} onChange={v=>setForm({...form,notes:v})}/><button className="primary">Transfer</button></Form><Table title="Transfer history" rows={rows} columns={['id','asset_code','from','to','quantity','transferred_at','notes']}/></Module>}

function Assignments(){return <SimpleTransaction type="assignments" title="Assign asset" fields={['asset_id','personnel_name','quantity']} />}
function Expenditures(){return <SimpleTransaction type="expenditures" title="Record expenditure" fields={['asset_id','quantity','reason']} />}
function SimpleTransaction({type,title,fields}){const [rows,setRows]=useState([]);const [assets,setAssets]=useState([]);const [form,setForm]=useState({quantity:1});const [msg,setMsg]=useState('');useEffect(()=>{Promise.all([api('/'+type),api('/assets')]).then(([r,a])=>{setRows(r);setAssets(a)})},[]);async function submit(e){e.preventDefault();try{const body={...form,asset_id:+form.asset_id,quantity:+form.quantity};await api('/'+type,{method:'POST',body:JSON.stringify(body)});setMsg('Saved successfully');setRows(await api('/'+type));setAssets(await api('/assets'))}catch(e){setMsg(e.message)}}return <Module title={title} msg={msg}><Form onSubmit={submit}><Select label="Asset" options={assets.map(a=>({...a,id:a.id,name:`${a.asset_code} — ${a.equipment_type} (${a.quantity})`}))} value={form.asset_id} onChange={v=>setForm({...form,asset_id:v})}/>{fields.filter(f=>f!=='asset_id').map(f=><Input key={f} label={f.replace('_',' ')} type={f==='quantity'?'number':'text'} value={form[f]||''} onChange={v=>setForm({...form,[f]:v})}/>)}<button className="primary">Save</button></Form><Table title="History" rows={rows} columns={Object.keys(rows[0]||{}).slice(0,7)}/></Module>}

function Assets(){const [rows,setRows]=useState([]);useEffect(()=>{api('/assets').then(setRows)},[]);return <Module title="Current asset inventory"><Table rows={rows} columns={['id','asset_code','equipment_type','base','status','quantity']}/></Module>}
function Audit(){const [rows,setRows]=useState([]);useEffect(()=>{api('/audit-logs').then(setRows)},[]);return <Module title="Audit trail"><Table rows={rows} columns={['id','user','action','entity','entity_id','details','created_at']}/></Module>}

function Module({title,msg,children}){return <><div className="section-title"><div><h3>{title}</h3><p className="muted">Use the controls below to manage records.</p></div>{msg&&<div className="toast">{msg}</div>}</div>{children}</>}
function Form({children,onSubmit}){return <form className="form-grid" onSubmit={onSubmit}>{children}</form>}
function Input({label,type='text',value,onChange}){return <label>{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} /></label>}
function Select({label,options,value,onChange}){return <label>{label}<select value={value||''} onChange={e=>onChange(e.target.value)}><option value="">Select...</option>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}
function Table({title,rows,columns=[]}){return <div className="table-card">{title&&<h3>{title}</h3>}{rows.length===0?<div className="empty">No records yet.</div>:<div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{columns.map(c=><td key={c}>{typeof r[c]==='object'&&r[c]!==null?new Date(r[c]).toLocaleString():String(r[c]??'—')}</td>)}</tr>)}</tbody></table></div>}</div>}
function Modal({title,onClose,children}){return <div className="overlay"><div className="modal"><div className="modal-head"><h3>{title}</h3><button onClick={onClose}>×</button></div>{children}</div></div>}
function Loader(){return <div className="loader">Loading...</div>}
export default App;
